config/routes.rb
Rails.application.routes.draw do
  get 'genres/index'
  get 'authors/show'
  get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root 'home#index'
  get '/about', to: 'about#about'
  resources :books
  resources :authors
  resources :genres
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/author.rb
class Author < ApplicationRecord
    validates :author_name, presence: true, length: { minimum: 5 }
    has_many :books
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :author
    belongs_to :genre
    has_many :publications, dependent: :destroy
    has_many :publishers, through: :publications
    validates :book_name, presence: true, length: { minimum: 5 }
  
    def self.search(query, author_id)
      if author_id.present?
        where('book_name LIKE ? AND author_id = ?', "%#{query}%", author_id)
      else
        where('book_name LIKE ?', "%#{query}%")
      end
    end
  end
  

app/models/genre.rb
class Genre < ApplicationRecord
    validates :genre_name, presence: true, length: { minimum: 5 }
    has_many :books
end

app/models/publication.rb
class Publication < ApplicationRecord
  belongs_to :book
  belongs_to :publisher
end

app/models/publisher.rb
class Publisher < ApplicationRecord
    validates :publisher_name, presence: true, length: { minimum: 5 }
    has_many :publications, dependent: :destroy
    has_many :books, through: :publications
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def index
    @authors = Author.all
  end

  def show
    @author = Author.find(params[:id])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @authors = Author.all
    if params[:search].present?
      @books = Book.includes(:author, :genre, :publishers)
                   .search(params[:search], params[:author_id])
                   .page(params[:page]).per(50)
      @no_results = @books.empty?
    else
      @books = Book.includes(:author, :genre, :publishers)
                   .page(params[:page]).per(50)
    end
    render 'books'
  end

  def show
    @book = Book.find(params[:id])
  end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  def index
    @genres = Genre.all
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/about/about.html.erb
<nav>
  <ul>
    <li><%= link_to 'Home', root_path %></li>
    <li><%= link_to 'About', about_path %></li>
    <li><%= link_to 'Books', books_path %></li>
    <li><%= link_to 'Authors', authors_path %></li>
    <li><%= link_to 'Genres', genres_path %></li>
  </ul>
</nav>

<h1>About Page</h1>
<p>Hi! We are a book library , we host a collection of great books, their authors, and a lot more information. Our library is free and accessible from anywhere in the world. </p>
<h3>Our mission:</h3>
<p> Our mission is to provide quality books and literature to everyone around the globe, and share knowledge.</p>
<h3>Contact us:</h3>
<ul> 
<li>Email: BookLibrary@gmail.com</li>
<li>Phone: 312-123-1231</li>
<li>In person: 200 Broadway street, Winnipeg </li>
</ul>
<h2>Data sources used: </h2>
<ul>
<li>Books CSV file.</li>
<li>Book Authors CSV.</li>
<li>Faker.</li>
</ul>

<h3>What every data source will be used for:</h3>
<p><strong>Faker </strong> : This data source is used to generate the book names, and publisher names.</p>
<ul>
<li>Table name = Books: Columns: book_id, book_name, author_id(FK), book_publisher(FK), genre_id(FK).</li>
<li>Table name = Publisher: Columns: publisher_id, publisher_name.</li>
</ul>
<p><strong>Books Authors CSV </strong> : This data source is used to pull the author names for the books.</p>
<ul>
<li>Table = Authors:  Columns: author_id, author name, author_birthdate.</li>
</ul>

<p><strong>Books CSV</strong> : This data source is used to pull the book genres names.</p>
<ul>
<li>Table= Genres: Columns: genre_id, genre_name..</li>
</ul>
<p><strong>Book Table and Publisher Table</strong> : Data will be pulled from both these tables and linked using the Publications table as a bridge.</p>
<ul>
<li>Table= Publications: publisher_id, book_id.
</li>
</ul>
<h4> How the data is related and integrated: </h4>
<p>The data that will be pulled from these different sources is related in a way that it is all about books. Data pulled from faker will provide book names and book publishers names. Data pulled from the Book_authors CSV will provide the books with author names. Lastly, the Book CSV file will be used to pull out book genres.</p>

<h3> ERD Diagram of the database: </h3>
<%= image_tag("Entity.jpg", alt: "ERD diagram of my books database") %>

app/views/authors/index.html.erb
<nav>
  <ul>
    <li><%= link_to 'Home', root_path %></li>
    <li><%= link_to 'About', about_path %></li>
    <li><%= link_to 'Books', books_path %></li>
    <li><%= link_to 'Authors', authors_path %></li>
    <li><%= link_to 'Genres', genres_path %></li>
  </ul>
</nav>
<h1>All Authors</h1>

<ul>
  <% @authors.each do |author| %>
    <li><%= link_to author.author_name, author_path(author) %></li>
  <% end %>
</ul>

app/views/authors/show.html.erb
<nav>
  <ul>
    <li><%= link_to 'Home', root_path %></li>
    <li><%= link_to 'About', about_path %></li>
    <li><%= link_to 'Books', books_path %></li>
    <li><%= link_to 'Authors', authors_path %></li>
    <li><%= link_to 'Genres', genres_path %></li>
  </ul>
</nav>
<h1><%= @author.author_name %></h1>
<p>Birthdate: <%= @author.author_birthdate %></p>

<h2>Books by <%= @author.author_name %>:</h2>
<ul>
  <% @author.books.each do |book| %>
    <li><%= link_to book.book_name, book_path(book) %></li>
  <% end %>
</ul>

app/views/books/books.html.erb
<nav>
  <ul>
    <li><%= link_to 'Home', root_path %></li>
    <li><%= link_to 'About', about_path %></li>
    <li><%= link_to 'Books', books_path %></li>
    <li><%= link_to 'Authors', authors_path %></li>
    <li><%= link_to 'Genres', genres_path %></li>
  </ul>
</nav>
<h1>All Books</h1>

<%= form_with(url: books_path, method: "get") do |form| %>
  <%= form.collection_select :author_id, Author.all, :id, :author_name, { include_blank: "Select an author" } %>
  <%= form.text_field :search, placeholder: "Search for a book by title" %>
  <%= form.submit "Search" %>
<% end %>


<table>
  <thead>
    <tr>
      <th>Book Name</th>
      <th>Author</th>
      <th>Publisher</th>
      <th>Genre</th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= link_to book.book_name, book_path(book) %></td>
        <td><%= link_to book.author.author_name, author_path(book.author) %></td>
        <td>
          <% book.publishers.each do |publisher| %>
            <%= publisher.publisher_name %><br>
          <% end %>
        </td>
        <td><%= book.genre.genre_name %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @books %>

app/views/books/show.html.erb
<nav>
  <ul>
    <li><%= link_to 'Home', root_path %></li>
    <li><%= link_to 'About', about_path %></li>
    <li><%= link_to 'Books', books_path %></li>
    <li><%= link_to 'Authors', authors_path %></li>
    <li><%= link_to 'Genres', genres_path %></li>
  </ul>
</nav>
<h1><%= @book.book_name %></h1>

<p>Book Name: <%= @book.book_name %> </p>
<p>Author: <%= link_to @book.author.author_name, author_path(@book.author) %></p>
<p>Genre: <%= @book.genre.genre_name %></p>

<% if @book.publishers.present? %>
  <p>Publishers Names:</p>
  <ul>
    <% @book.publishers.each do |publisher| %>
      <li><%= publisher.publisher_name %></li>
    <% end %>
  </ul>
<% end %>

app/views/genres/index.html.erb
<nav>
  <ul>
    <li><%= link_to 'Home', root_path %></li>
    <li><%= link_to 'About', about_path %></li>
    <li><%= link_to 'Books', books_path %></li>
    <li><%= link_to 'Authors', authors_path %></li>
    <li><%= link_to 'Genres', genres_path %></li>
  </ul>
</nav>
<h1>All Genres</h1>

<ul>
  <% @genres.each do |genre| %>
    <li>Genre Name:<strong> <%= genre.genre_name%></strong> </li>
  <% end %>
</ul>

app/views/home/index.html.erb
<nav>
  <ul>
    <li><%= link_to 'Home', root_path %></li>
    <li><%= link_to 'About', about_path %></li>
    <li><%= link_to 'Books', books_path %></li>
    <li><%= link_to 'Authors', authors_path %></li>
    <li><%= link_to 'Genres', genres_path %></li>
  </ul>
</nav>

<h1>Welcome to the books page</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Store</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>